# Please do not move these numbers
version: "1.0"

commands:
  me:
    description: "Send a message with your name"
    permission: "pocketmine.command.me"

    # set permission: none for EVERYONE can use command
    message: "[ME] {SENDER}: {MESSAGE}"
  say:
    description: "Send a message"
    permission: "pocketmine.command.say"
    # set permission: none for EVERYONE can use command

    message: "[{PREFIX}] {MESSAGE}"
    types:
      server: # This is the default tag, update the "show" if you want
        show: "SERVER"
      # The type argument modifies the word SERVER in front of the SAY message, if you want to create several prefixes define here
      # Default: server (no type, just message /say blablablabla)
      # Exemple: /say test MY CAT IS BEAUTIFUL
      # Chat: [TESTT] MY CAT IS BEAUTIFUL
      test:
        show: "TESTT"